### ISSUE TITLE
Can't receive text and links on Mac

### ISSUE THREAD

**Issue by stanleylhs** [grishka/NearDrop#16] opened 2023-04-15 05:10 UTC
Description:
Can't receive text

![image](https://user-images.githubusercontent.com/4337525/232184308-f2f3c05a-9d2c-42c6-93b0-350ea7866c75.png)

The operation couldn't be completed.
(SwiftProtobuf.BinaryDecodingErrorerror3.)

Steps:
1. Copy any text or link
2. Click Share, Nearby share 
3. Click the NearDrop device
4. See error on Mac

**Comment by mbrammer** [comment] 2023-04-15 07:31
Just tried the same :)  
Would be nice if links would be opened in the default browser and text copied to the clipboard or opened in a default text editor. But I personally would prefer the clipboard solution.

Anyways, thank you very much for this application. I was waiting a long time for a easy sharing between Mac and Android 🙏

**Comment by mbrammer** [comment] 2023-04-15 07:33
Just saw this issue is a duplicate of https://github.com/grishka/NearDrop/issues/3

**Comment by sannidhyaroy** [comment] 2023-04-15 17:30
+1
The expected behavior when links are shared should be to open it in the default browser...

**Comment by sannidhyaroy** [comment] 2023-04-16 06:22
> In android it depends how you should share this text/url.
> 
> For example if you have a url, how would you share it? Do you create a file on your smartphone, put the url text in the file, save the file and then share the file?

When you tap on the share button on a browser or basically any webpage on Android, it would send a url to that page through Nearby Share. I think you can replicate what KDE Connect does at this point. It checks whether the received data is a file, a url or a text and then does what's appropriate.

Not sure if this would be helpful for you, but [here's the code](https://github.com/soduto/Soduto/blob/89d672ec849a20e835a3cec13c4fd09c742a50e0/Soduto/Services/ShareService.swift#L78) how Soduto (a macOS KDE Connect Client app) handles the received data packets.

**Closed** 2023-09-26 01:58 UTC

**Comment by avaidyam** [comment] 2023-09-26 22:43
FYI Nearby Share (unlike AirDrop) [does support sharing text between devices](https://9to5google.com/2023/05/23/nearby-share-copy-send-text/) (received text is indeed copied to the clipboard and NOT saved as a file). I think it's still worth adding this as a feature.
